name: encode-handler pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - uses: actions/setup-go@v2
      name: Setup Golang env
    - name: Test
      run: |
        go test .

